INSERT INTO [dbo].[Image]
   ([Id]
   ,[ImageId]
   ,[FileExtension]
   ,[Class]
   ,[IndexSource]
   ,[Who]
   ,[ResolutionX]
   ,[ResolutionY]
   ,[TagsString]
   ,[DateDownloaded]
   ,[Reported]
   ,[Ratio]
   ,[Downloads]
   ,[Hash]
   ,[ServerId]
   ,[IsThumbnailAvailable]
   ,[IsLockedImage]
   ,[Size]
   ,[SourceUrl])
VALUES
   (@Id
   ,@ImageId
   ,@FileExtension
   ,@Class
   ,@IndexSource
   ,@Who
   ,@ResolutionX
   ,@ResolutionY
   ,@TagsString
   ,@DateDownloaded
   ,@Reported
   ,@Ratio
   ,@Downloads
   ,@Hash
   ,@ServerId
   ,@IsThumbnailAvailable
   ,@IsLockedImage
   ,@Size
   ,@SourceUrl)