CREATE TABLE [dbo].[UpdateRequest]
(
	[Id] INT NOT NULL PRIMARY KEY, 
    [UserId] UNIQUEIDENTIFIER NULL, 
    [IpAddress] NVARCHAR(128) NOT NULL, 
    [Key] NVARCHAR(16) NOT NULL, 
    [Value] NVARCHAR(512) NOT NULL
)
